sudo: required
services:
  - docker

before_install:
  - docker build -t karlsobak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karlsobak/docker-react npm run test -- --coverage